version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin123
    # ports:
      # - "5432:5432"

  app:
    build: .
    container_name: emp-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/mydb
      - DB_USERNAME=postgres
      - DB_PASSWORD=Admin123
