### Base URL
@baseUrl = http://localhost:8080/api


### Get all departments
GET {{baseUrl}}/departments
Accept: application/json


### Delete Department (valid)
DELETE {{baseUrl}}/departments/10
Accept: application/json


### Delete Department (invalid)
DELETE {{baseUrl}}/departments/999
Accept: application/json


### Create Department (Success)
POST {{baseUrl}}/departments
Content-Type: application/json

{
    "name": "IT"
}


### Create Department (Failure - Duplicate ID)
POST {{baseUrl}}/departments
Content-Type: application/json

{
    "name": "IT"
}


### Empty Department name (bad request)
POST {{baseUrl}}/departments
Content-Type: application/json

{
    "name": ""
}


### Employee Endpoints

### Get all employees
GET {{baseUrl}}/employees
Accept: application/json


### Get all employees with pagination
GET {{baseUrl}}/employees?page=0&size=5
Accept: application/json


### Get all employees in sorted order
GET {{baseUrl}}/employees?sort=name,asc
Accept: application/json


### Get all employees in sorted order with pagination
GET {{baseUrl}}/employees?page=0&size=5&sort=name,asc
Accept: application/json


### Create a new employee
POST {{baseUrl}}/employees
Content-Type: application/json

{
    "name": "John Doe 6",
    "email": "john.doe6@example.com",
    "departmentId": 12
}


### Create a new employee with non-existing department
POST {{baseUrl}}/employees
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",
    "departmentId": 999
}


### Create Employee with missing email (bad request)
POST {{baseUrl}}/employees
Content-Type: application/json

{
    "name": "John Doe",
    "department": 10
}


### Get employees by department
GET {{baseUrl}}/employees?departmentId=12
Accept: application/json


### Get employees by non-existing department (should return empty list)
GET {{baseUrl}}/employees?departmentId=999
Accept: application/json


### Get employee by ID (valid)
GET {{baseUrl}}/employees/9
Accept: application/json


### Get employee by ID (invalid)
GET {{baseUrl}}/employees/999
Accept: application/json


### Update an existing employee (valid)
PUT {{baseUrl}}/employees/9
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe.updated@example.com",
    "departmentId": 12
}

### Update an existing employee with non-existing department
PUT {{baseUrl}}/employees/9
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe.updated@example.com",
    "departmentId": 10
}


### Delete an employee (valid)
DELETE {{baseUrl}}/employees/9
Accept: application/json


### Delete an employee (invalid)
DELETE {{baseUrl}}/employees/999
Accept: application/json



### Edge cases
### Empty body for creating employee (bad request)
POST {{baseUrl}}/employees
Content-Type: application/json

{}

### Empty body for creating department (bad request)
POST {{baseUrl}}/departments
Content-Type: application/json

{}


### Empty body for updating employee (bad request)
PUT {{baseUrl}}/employees/1
Content-Type: application/json

{}


### Empty body for updating department (bad request)
PUT {{baseUrl}}/departments/1
Content-Type: application/json

{}


### Wrong enpoint
GET {{baseUrl}}/employee
Accept: application/json